# Generated by Django 5.0.6 on 2024-12-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionplan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_profiles',
            field=models.IntegerField(),
        ),
    ]
