# Generated by Django 5.0.6 on 2024-12-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_subscriptionplan_max_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_profiles',
            field=models.IntegerField(default=1),
        ),
    ]
