# Generated by Django 5.0.6 on 2025-01-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='valid_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
