# Generated by Django 5.0.6 on 2025-01-29 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_payment_valid_until_subscriptionplan_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_devices',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
