# Generated by Django 5.0.6 on 2024-05-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Default Name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='profile', to='userauths.profile'),
        ),
    ]
